//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp2.SkuService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SkuService.SkuClientSoap")]
    public interface SkuClientSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ConsoleApp2.SkuService.HelloWorldResponse HelloWorld(ConsoleApp2.SkuService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp2.SkuService.HelloWorldResponse> HelloWorldAsync(ConsoleApp2.SkuService.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetSkuDetailResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSkuDetail", ReplyAction="*")]
        ConsoleApp2.SkuService.GetSkuDetailResponse GetSkuDetail(ConsoleApp2.SkuService.GetSkuDetailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSkuDetail", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp2.SkuService.GetSkuDetailResponse> GetSkuDetailAsync(ConsoleApp2.SkuService.GetSkuDetailRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp2.SkuService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ConsoleApp2.SkuService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp2.SkuService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ConsoleApp2.SkuService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSkuDetailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSkuDetail", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp2.SkuService.GetSkuDetailRequestBody Body;
        
        public GetSkuDetailRequest() {
        }
        
        public GetSkuDetailRequest(ConsoleApp2.SkuService.GetSkuDetailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSkuDetailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long itemId;
        
        public GetSkuDetailRequestBody() {
        }
        
        public GetSkuDetailRequestBody(long itemId) {
            this.itemId = itemId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSkuDetailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSkuDetailResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp2.SkuService.GetSkuDetailResponseBody Body;
        
        public GetSkuDetailResponse() {
        }
        
        public GetSkuDetailResponse(ConsoleApp2.SkuService.GetSkuDetailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSkuDetailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSkuDetailResult;
        
        public GetSkuDetailResponseBody() {
        }
        
        public GetSkuDetailResponseBody(string GetSkuDetailResult) {
            this.GetSkuDetailResult = GetSkuDetailResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SkuClientSoapChannel : ConsoleApp2.SkuService.SkuClientSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SkuClientSoapClient : System.ServiceModel.ClientBase<ConsoleApp2.SkuService.SkuClientSoap>, ConsoleApp2.SkuService.SkuClientSoap {
        
        public SkuClientSoapClient() {
        }
        
        public SkuClientSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SkuClientSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SkuClientSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SkuClientSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp2.SkuService.HelloWorldResponse ConsoleApp2.SkuService.SkuClientSoap.HelloWorld(ConsoleApp2.SkuService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ConsoleApp2.SkuService.HelloWorldRequest inValue = new ConsoleApp2.SkuService.HelloWorldRequest();
            inValue.Body = new ConsoleApp2.SkuService.HelloWorldRequestBody();
            ConsoleApp2.SkuService.HelloWorldResponse retVal = ((ConsoleApp2.SkuService.SkuClientSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp2.SkuService.HelloWorldResponse> ConsoleApp2.SkuService.SkuClientSoap.HelloWorldAsync(ConsoleApp2.SkuService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp2.SkuService.HelloWorldResponse> HelloWorldAsync() {
            ConsoleApp2.SkuService.HelloWorldRequest inValue = new ConsoleApp2.SkuService.HelloWorldRequest();
            inValue.Body = new ConsoleApp2.SkuService.HelloWorldRequestBody();
            return ((ConsoleApp2.SkuService.SkuClientSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp2.SkuService.GetSkuDetailResponse ConsoleApp2.SkuService.SkuClientSoap.GetSkuDetail(ConsoleApp2.SkuService.GetSkuDetailRequest request) {
            return base.Channel.GetSkuDetail(request);
        }
        
        public string GetSkuDetail(long itemId) {
            ConsoleApp2.SkuService.GetSkuDetailRequest inValue = new ConsoleApp2.SkuService.GetSkuDetailRequest();
            inValue.Body = new ConsoleApp2.SkuService.GetSkuDetailRequestBody();
            inValue.Body.itemId = itemId;
            ConsoleApp2.SkuService.GetSkuDetailResponse retVal = ((ConsoleApp2.SkuService.SkuClientSoap)(this)).GetSkuDetail(inValue);
            return retVal.Body.GetSkuDetailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp2.SkuService.GetSkuDetailResponse> ConsoleApp2.SkuService.SkuClientSoap.GetSkuDetailAsync(ConsoleApp2.SkuService.GetSkuDetailRequest request) {
            return base.Channel.GetSkuDetailAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp2.SkuService.GetSkuDetailResponse> GetSkuDetailAsync(long itemId) {
            ConsoleApp2.SkuService.GetSkuDetailRequest inValue = new ConsoleApp2.SkuService.GetSkuDetailRequest();
            inValue.Body = new ConsoleApp2.SkuService.GetSkuDetailRequestBody();
            inValue.Body.itemId = itemId;
            return ((ConsoleApp2.SkuService.SkuClientSoap)(this)).GetSkuDetailAsync(inValue);
        }
    }
}
